"options":
  "ssh-hostname":
    "type": "string"
    "default": ""
    "description": "The hostname or IP address of the machine to"
  "ssh-username":
    "type": "string"
    "default": ""
    "description": "The username to login as."
  "ssh-password":
    "type": "string"
    "default": ""
    "description": "The password used to authenticate."
  "ssh-private-key":
    "type": "string"
    "default": ""
    "description": "DEPRECATED. The private ssh key to be used to authenticate."
  "ssh-public-key":
    "type": "string"
    "default": ""
    "description": "The public key of this unit."
  "ssh-key-type":
    "type": "string"
    "default": "rsa"
    "description": "The type of encryption to use for the SSH key."
  "ssh-key-bits":
    "type": "int"
    "default": !!int "4096"
    "description": "The number of bits to use for the SSH key."
  "listen_port":
    "type": "int"
    "default": !!int "51820"
    "description": "UDP port to listen for peers on"
  "tunnel_address":
    "type": "string"
    "default": "10.0.0.1/24"
    "description": "Interface tunnel address"
  "tunnel_id":
    "type": "string"
    "default": "1"
    "description": "Tunnel VNF ID"
  "vsi_id":
    "type": "string"
    "default": "1"
    "description": "Current VSI ID"
  "bandwidth":
    "type": "string"
    "default": "1000"
    "description": "Tunnel Bandwidth"
  "use_data_interfaces":
    "type": "boolean"
    "default": !!bool "true"
    "description": "Use Data Interfaces"
  "data_address":
    "type": "string"
    "default": "127.0.0.1/24"
    "description": "Interface tunnel address"
  "data_interface":
    "type": "string"
    "default": "error"
    "description": "Interface the tunnel will use"
  # client_tunnel_address:
  #   type: string
  #   default: "10.0.0.2/24"
  #   description: "Interface client address"
  # server_public_address:
  #   type: string
  #   default: "192.168.85.1/24"
  #   description: "Interface client address"
  "forward_interface":
    "type": "string"
    "default": "wg0"
    "description": "Interface to forward packets on"
  "save_config":
    "type": "boolean"
    "default": !!bool "true"
    "description": "Configuration file should be saved on shutdown using the current\
      \ status of the interface"
  # wg_server:
  #   type: boolean
  #   default: !!bool "true"
  #   description: "Specify if the charm should be configured as a server or client"
